version: '3.5'

services:
  university:
    build:
      context: .
      dockerfile: docker/university/Dockerfile
    image: university
    container_name: university
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"
